[metadata]
name = mlmd
version = 0.0.1
author = Bruno Cuevas
author_email = brunocuevaszuviria@gmail.com
description = ML for molecular dynamics
long_description = file: README.md
long_description_content_type = text/markdown
url =
project_urls =
    Bug Tracker =
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = mlmd, scripts
python_requires = >=3.9
install_requires =
    click
    numpy
    pandas
    PyYAML
    tqdm
    MDAnalysis
    torch
    torch-geometric
include_package_data = True
[options.entry_points]
console_scripts =
    mlmd-train = scripts.run:train
